name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Use requirements.txt if present
      - name: Install from requirements.txt
        if: hashFiles('requirements.txt') != ''
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Otherwise install needed tools directly
      - name: Install pytest + flake8
        if: hashFiles('requirements.txt') == ''
        run: |
          python -m pip install --upgrade pip
          pip install pytest==8.3.3 flake8==7.1.1

      - name: Lint
        run: flake8 .

      - name: Run tests
        run: pytest -q
