name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # If you don't have requirements.txt, this installs tools directly
      - name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt


      # Ensure repo root is on Python path (belt + suspenders)
      - name: Add repo to PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Lint
        run: flake8 .

      - name: Run tests
        run: pytest
