name: Release (TestPyPI on main, PyPI on tags)

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build artifacts (wheel + sdist)
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build

      # If this is a tag like v1.2.3 -> publish to PyPI
      - name: Publish to PyPI (on tags)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      # Else (push to main without tag) -> publish to TestPyPI
      - name: Publish to TestPyPI (on main)
        if: github.ref == 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
